service: openapi-status-check
provider:
  name: aws
  runtime: python3.8
  region: eu-central-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  openapi_check:      
    handler: handler.run
    events:
      - http:
          path: run
          method: get
      - schedule: rate(5 minutes)

plugins:
  - serverless-python-requirements
